### ISSUE TITLE
Filled_Maps don't get emissive,

### ISSUE THREAD

**Issue by Frustrated-Programmer** [BluebirdYT/emissive-library#1]
Despite loading custom textures to the map with their alpha channels set to 254 and seeing them change in game, they are not emissive. I have no idea on how I'd make the "colors" of the map be set to 254 and if you have ideas let me know,
but changing the background & markings to alpha 254 doesn't make them emissive in game.

**Comment by BluebirdDevs** [comment]
Do you mean the map marking of a filled map or the actual map picture?

**Comment by Frustrated-Programmer** [comment]
Both. You can see here that the filled_map is taking my test resource(pink) but it isn't emissive.
![image](https://github.com/user-attachments/assets/8015d87c-f5ff-4962-9585-d382c84b2e74)

The end goal is to ALSO get the map markings also emissive, but I do not know if that is possible and am just testing things. If you have ideas on how I could do that lmk.

**Comment by BluebirdDevs** [comment]
I can fix the pink part on the map easily, the map markings on the other hand would not work due to them being translucent already and other reasons that are hard to explain.

See if the updated attached resourcepack allows for the pink part to be emissive.


[Emissive Library v0.1.2-alpha.zip](https://github.com/user-attachments/files/18204112/Emissive.Library.v0.1.2-alpha.zip)

**Comment by BluebirdDevs** [comment]
If the attached pack above did not work feel free to reopen this ticket. This pack is unable to support the map markings texture due to the way it was coded.
